### ISSUE TITLE
Missing FEM book

### ISSUE THREAD

**Issue by freevryheid** [Beliavsky/Fortran-related-books#2]
The Finite Element Method Displayed
by [Gouri Dhatt](https://www.betterworldbooks.com/search/results?q=Gouri%20Dhatt), [Gilbert Touzot](https://www.betterworldbooks.com/search/results?q=Gilbert%20Touzot)

This is the first edition. Not sure about later editions. This got me started using FORTRAN. 
The code from the book is in my repo: https://github.com/freevryheid/FEM/tree/master/DT
Had to modify it slightly to run on WATFOR or Microsoft Fortran - can't remember, it's been a while.

BTW - thanks for excellent list, posted this as I see you as the official fortran chronologer :)

**Comment by Beliavsky** [comment]
Added the book and a link to your repo. I'm glad you like the list.
